spring:
  application:
    name: cwa-testresult-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testresult
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.yml
server:
  servlet:
    context-path: /test-results-api
springdoc:
  api-docs:
    path: /api-docs/docs
  swagger-ui:
    path: /api-docs/swagger
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  health:
    probes:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
testresult:
  cleanup:
    delete:
      days: 10          # 10 days old
      rate: 3600000     # every hour
cloud:
  aws:
    region:
      static: eu-central-1
